import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Wrench, Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Card } from "@/components/ui/card";
import * as LucideIcons from "lucide-react";

interface Trade {
  id: string;
  slug: string;
  name: string;
  category: string;
  icon_name: string;
  description: string | null;
}

const CATEGORY_LABELS: Record<string, string> = {
  exterior: "Exterior",
  interior: "Interior",
  kitchen_bath: "Kitchen & Bath",
  specialty: "Specialty",
  emergency: "Emergency",
};

function getIcon(name: string) {
  const Icon = (LucideIcons as any)[name?.charAt(0).toUpperCase() + name?.slice(1)] ||
    (LucideIcons as any)[name] ||
    Wrench;
  return Icon;
}

export default function ServicesGrid() {
  const [trades, setTrades] = useState<Trade[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      const { data } = await supabase
        .from("iq_trades")
        .select("id, slug, name, category, icon_name, description")
        .eq("active", true)
        .order("sort_order");
      setTrades((data || []) as Trade[]);
      setLoading(false);
    })();
  }, []);

  const grouped = trades.reduce<Record<string, Trade[]>>((acc, t) => {
    (acc[t.category] = acc[t.category] || []).push(t);
    return acc;
  }, {});

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b bg-card/60 backdrop-blur sticky top-0 z-10">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link to="/member/dashboard" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground">
            <ArrowLeft className="h-4 w-4" /> Return to Dashboard
          </Link>
          <h1 className="text-lg font-semibold">Instant Quote</h1>
          <div className="w-32" />
        </div>
      </header>

      <main className="container mx-auto px-4 py-10">
        <div className="text-center mb-10">
          <h2 className="text-3xl md:text-4xl font-bold tracking-tight">Pick a service to get an instant ballpark</h2>
          <p className="text-muted-foreground mt-3 max-w-2xl mx-auto">
            AI measures, scans photos, and prices any project — roofing, interiors, exteriors, and specialty work.
          </p>
        </div>

        {loading ? (
          <div className="flex justify-center py-20"><Loader2 className="h-6 w-6 animate-spin" /></div>
        ) : (
          <div className="space-y-10">
            {Object.entries(grouped).map(([cat, list]) => (
              <section key={cat}>
                <h3 className="text-xl font-semibold mb-4">{CATEGORY_LABELS[cat] || cat}</h3>
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                  {list.map((t) => {
                    const Icon = getIcon(t.icon_name);
                    return (
                      <Link key={t.id} to={`/instant-quote/${t.slug}`}>
                        <Card className="p-5 h-full hover:shadow-lg hover:border-primary transition-all cursor-pointer group">
                          <div className="h-10 w-10 rounded-lg bg-primary/10 text-primary flex items-center justify-center mb-3 group-hover:scale-110 transition-transform">
                            <Icon className="h-5 w-5" />
                          </div>
                          <div className="font-semibold">{t.name}</div>
                          {t.description && (
                            <p className="text-xs text-muted-foreground mt-1 line-clamp-2">{t.description}</p>
                          )}
                        </Card>
                      </Link>
                    );
                  })}
                </div>
              </section>
            ))}
          </div>
        )}

        <p className="text-xs text-muted-foreground text-center mt-12 max-w-3xl mx-auto">
          All quotes are non-binding ballpark estimates generated by AI. Final pricing is provided by the licensed
          contractor performing the work after on-site inspection.
        </p>
      </main>
    </div>
  );
}
