// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List all contractor services offered by Global Contractor Network with their quote page URLs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const services = [
      { name: "Roofing (Residential)", path: "/roofing?type=residential" },
      { name: "Roofing (Commercial)", path: "/roofing?type=commercial" },
      { name: "Roof Coating (Residential)", path: "/coating-kings?propertyType=residential" },
      { name: "Roof Coating (Commercial)", path: "/coating-kings?propertyType=commercial" },
      { name: "Impact Windows & Doors (Residential)", path: "/green-home-solutions?type=residential" },
      { name: "Impact Windows & Doors (Commercial)", path: "/green-home-solutions?type=commercial" },
      { name: "Tree Removal & Landscaping", path: "/northern-landscaping" },
      { name: "Emergency Mitigation / Mold / Water Damage", path: "/emergency-mitigation" },
      { name: "Permit Processing", path: "/permit-queens" },
      { name: "Insurance Claim Supplements", path: "/supplement-kings" },
      { name: "Contractor Directory", path: "/directory" },
      { name: "Training Academy", path: "/academy" }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
      structuredContent: { services }
    };
  }
});

// src/lib/mcp/tools/search-contractors.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var search_contractors_default = defineTool2({
  name: "search_contractors",
  title: "Search contractors",
  description: "Search verified contractors in the Global Contractor Network directory by service category and optional location.",
  inputSchema: {
    category: z.enum([
      "Roofing",
      "Windows & Doors",
      "Tree Service",
      "Landscaping",
      "General Contractor",
      "Electrical",
      "Plumbing",
      "HVAC",
      "Painting",
      "Flooring"
    ]).describe("Service category to search for."),
    location: z.string().optional().describe("City, area, or ZIP code to filter results."),
    limit: z.number().int().min(1).max(20).optional().describe("Max results to return (default 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ category, location, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Backend not configured" }], isError: true };
    }
    const supabase = createClient(url, key, { auth: { persistSession: false } });
    const { data, error } = await supabase.from("contractor_profiles").select("id, company_name, category, average_rating, is_verified, phone, email, service_area, price_tier").eq("category", category).order("average_rating", { ascending: false, nullsFirst: false }).limit(limit ?? 5);
    if (error) {
      return { content: [{ type: "text", text: `Search failed: ${error.message}` }], isError: true };
    }
    let results = data ?? [];
    if (location && results.length) {
      const loc = location.toLowerCase();
      results = results.filter((c) => {
        const areas = Array.isArray(c.service_area) ? c.service_area : [];
        return areas.length === 0 || areas.some((a) => String(a).toLowerCase().includes(loc));
      });
    }
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, contractors: results }
    };
  }
});

// src/lib/mcp/tools/get-service-areas.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_service_areas_default = defineTool3({
  name: "get_service_areas",
  title: "Get service areas",
  description: "Return the geographic service areas covered by the Global Contractor Network.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const areas = {
      primary: "South Florida",
      counties: ["Miami-Dade", "Broward", "Palm Beach"],
      notes: "Additional Florida markets supported via partner contractor network."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(areas, null, 2) }],
      structuredContent: areas
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "gcn-mcp",
  title: "Global Contractor Network",
  version: "0.1.0",
  instructions: "Tools for the Global Contractor Network platform. Use `list_services` to see available contractor services and their quote page paths, `search_contractors` to find verified contractors by category and location, and `get_service_areas` to see supported geographic areas.",
  tools: [list_services_default, search_contractors_default, get_service_areas_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
