
-- Add missing roofing-specific and form-fill columns to permit_projects
ALTER TABLE public.permit_projects
  ADD COLUMN IF NOT EXISTS roof_size_sqft numeric NULL,
  ADD COLUMN IF NOT EXISTS roof_pitch text NULL,
  ADD COLUMN IF NOT EXISTS roof_stories integer NULL,
  ADD COLUMN IF NOT EXISTS existing_roof_material text NULL,
  ADD COLUMN IF NOT EXISTS new_roof_material text NULL,
  ADD COLUMN IF NOT EXISTS underlayment_product text NULL,
  ADD COLUMN IF NOT EXISTS underlayment_noa text NULL,
  ADD COLUMN IF NOT EXISTS roof_covering_product text NULL,
  ADD COLUMN IF NOT EXISTS roof_covering_noa text NULL,
  ADD COLUMN IF NOT EXISTS fastener_product text NULL,
  ADD COLUMN IF NOT EXISTS fastener_noa text NULL,
  ADD COLUMN IF NOT EXISTS deck_type text NULL,
  ADD COLUMN IF NOT EXISTS obstacles text NULL,
  ADD COLUMN IF NOT EXISTS is_hvhz boolean NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hvhz_protocol text NULL,
  ADD COLUMN IF NOT EXISTS energy_code_compliant boolean NULL,
  ADD COLUMN IF NOT EXISTS engineer_required boolean NULL,
  ADD COLUMN IF NOT EXISTS owner_address text NULL,
  ADD COLUMN IF NOT EXISTS owner_city text NULL,
  ADD COLUMN IF NOT EXISTS owner_state text NULL,
  ADD COLUMN IF NOT EXISTS owner_zip text NULL,
  ADD COLUMN IF NOT EXISTS owner_fax text NULL,
  ADD COLUMN IF NOT EXISTS folio_number text NULL,
  ADD COLUMN IF NOT EXISTS legal_description text NULL,
  ADD COLUMN IF NOT EXISTS flood_zone text NULL,
  ADD COLUMN IF NOT EXISTS wind_speed_zone text NULL,
  ADD COLUMN IF NOT EXISTS square_footage numeric NULL,
  ADD COLUMN IF NOT EXISTS roof_work_type text NULL,
  ADD COLUMN IF NOT EXISTS window_count integer NULL,
  ADD COLUMN IF NOT EXISTS door_count integer NULL,
  ADD COLUMN IF NOT EXISTS sliding_door_count integer NULL,
  ADD COLUMN IF NOT EXISTS frame_material text NULL,
  ADD COLUMN IF NOT EXISTS u_factor text NULL,
  ADD COLUMN IF NOT EXISTS shgc text NULL,
  ADD COLUMN IF NOT EXISTS window_product text NULL,
  ADD COLUMN IF NOT EXISTS window_noa text NULL,
  ADD COLUMN IF NOT EXISTS door_product text NULL,
  ADD COLUMN IF NOT EXISTS door_noa text NULL,
  ADD COLUMN IF NOT EXISTS improvement_description text NULL,
  ADD COLUMN IF NOT EXISTS lender_name text NULL,
  ADD COLUMN IF NOT EXISTS lender_address text NULL,
  ADD COLUMN IF NOT EXISTS bond_amount text NULL,
  ADD COLUMN IF NOT EXISTS surety_name text NULL;
