// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ujalvgknnbsxqpujxvwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqYWx2Z2tubmJzeHFwdWp4dndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2OTMzMDcsImV4cCI6MjA3NTI2OTMwN30.sh41h6hP_JNkRifubmKsrmr0Pr4tbshfK-gnR_BLNLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const supabase: any = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
