// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// NOTE: Pointed at the user-owned Supabase project (lhsmeevflgrqizkchhpu)
// rather than the legacy auto-provisioned Lovable Cloud project.
// The auto-generated `Database` type in ./types reflects the OLD project's
// schema, so we deliberately use an untyped client here to allow queries
// against the new project's `permit_*` tables.
const SUPABASE_URL = "https://lhsmeevflgrqizkchhpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxoc21lZXZmbGdycWl6a2NoaHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1NjM3MTAsImV4cCI6MjA4MjEzOTcxMH0.TTeeM--VWGelIaJSOWuJD8O1a8TKSlDdllR3KKmty8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const supabase: any = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
